spring:
  profiles:
    active: dev
  datasource:
    driver-c1ass-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/dbstudent
    username : root
    password: root
  jpa :
    hibernate:
      ddl-auto: update
    show-sql: true

